name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Clear npm cache and remove lock file to avoid optional dependency issues
          npm cache clean --force
          rm -f package-lock.json
          npm install

      - name: Build component library
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      # Release deployment (root) - only for tags
      - name: Setup Pages (Release)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/configure-pages@v4

      - name: Upload Storybook to Pages (Release)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-pages-artifact@v3
        with:
          path: './storybook-static'

      - name: Deploy to GitHub Pages (Release)
        if: startsWith(github.ref, 'refs/tags/v')
        id: deployment
        uses: actions/deploy-pages@v4

      # Also deploy release to versioned directory
      - name: Deploy release to versioned directory
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Setup authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          # Get the tag name (remove refs/tags/ prefix)
          TAG_NAME=${GITHUB_REF#refs/tags/}

          # Fetch and checkout gh-pages branch (create if doesn't exist)
          git fetch origin gh-pages:gh-pages 2>/dev/null || git checkout --orphan gh-pages
          git checkout gh-pages 2>/dev/null || echo "Created new gh-pages branch"

          # Create versioned directory and copy files
          VERSION_DIR="$TAG_NAME"
          mkdir -p "$VERSION_DIR"
          cp -r storybook-static/* "$VERSION_DIR/"

          # Add and commit
          git add "$VERSION_DIR"
          git commit -m "Deploy release $TAG_NAME to $VERSION_DIR directory" || echo "No changes to commit"

          # Push to gh-pages
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Main branch deployment (main directory)
      - name: Deploy main branch to subdirectory
        if: github.ref == 'refs/heads/main'
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Setup authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          # Fetch and checkout gh-pages branch (create if doesn't exist)
          git fetch origin gh-pages:gh-pages 2>/dev/null || git checkout --orphan gh-pages
          git checkout gh-pages 2>/dev/null || echo "Created new gh-pages branch"

          # Create main directory and copy files
          MAIN_DIR="main"
          mkdir -p "$MAIN_DIR"
          cp -r storybook-static/* "$MAIN_DIR/"

          # Add and commit
          git add "$MAIN_DIR"
          git commit -m "Deploy main branch to $MAIN_DIR directory" || echo "No changes to commit"

          # Push to gh-pages
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # PR deployment (subdirectory)
      - name: Deploy PR to subdirectory
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Setup authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          # Fetch gh-pages branch or create it if it doesn't exist
          git fetch origin gh-pages:gh-pages 2>/dev/null || {
            echo "Creating new gh-pages branch"
            git checkout --orphan gh-pages
            git rm -rf . 2>/dev/null || true
          }

          # Checkout gh-pages properly (not detached)
          git checkout gh-pages 2>/dev/null || {
            echo "Switched to new gh-pages branch"
          }

          # Create PR directory and copy files
          PR_DIR="pr-${{ github.event.number }}"
          rm -rf "$PR_DIR" 2>/dev/null || true  # Remove existing directory
          mkdir -p "$PR_DIR"
          cp -r storybook-static/* "$PR_DIR/"

          # Add and commit
          git add "$PR_DIR"
          git commit -m "Deploy PR #${{ github.event.number }} to $PR_DIR" || echo "No changes to commit"

          # Push to gh-pages
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Cleanup PR directory when PR is closed
      - name: Cleanup PR directory
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Setup authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          # Fetch and checkout gh-pages branch
          git fetch origin gh-pages:gh-pages || echo "gh-pages branch doesn't exist"
          git checkout gh-pages || exit 0

          # Remove PR directory
          PR_DIR="pr-${{ github.event.number }}"
          if [ -d "$PR_DIR" ]; then
            rm -rf "$PR_DIR"
            git add .
            git commit -m "Remove PR #${{ github.event.number }} directory ($PR_DIR)"
            git push origin gh-pages
            echo "Removed $PR_DIR directory"
          else
            echo "$PR_DIR directory not found"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR with preview link
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;
            const previewUrl = `https://${repoOwner}.github.io/${repoName}/pr-${prNumber}/`;

            const comment = `🚀 **Storybook Preview Deployed!**

            Preview this PR's changes at: ${previewUrl}

            This preview will be updated automatically when you push new commits to this PR.`;

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: repoOwner,
              repo: repoName,
              body: comment
            });
